# Generated by Django 5.0.3 on 2024-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_friendrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_typing',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
